In [1]:
import sklearn
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
data=pd.read_csv("real_estate_properties.csv")

In [3]:
data

,Unnamed: 0,Name,Area,Furnishing,Transaction,Status,Price
0,0,4 BHK Apartment for Sale in Sugam Morya,1850 sqft,Unfurnished,Resale,Ready to Move,₹2.38 Cr
1,1,2 BHK Apartment for Sale in Regent Park Kolkata,525 sqft,Unfurnished,Resale,Ready to Move,₹32 Lac
2,2,2 BHK Apartment for Sale in Parvati Garden,705 sqft,Unfurnished,Resale,Ready to Move,₹32 Lac
3,3,3 BHK Apartment for Sale in Multicon Estelle,1612 sqft,Unfurnished,Resale,Ready to Move,₹2.25 Cr
4,4,2 BHK Apartment for Sale in Golpark Cooperativ...,980 sqft,Semi-Furnished,Resale,Ready to Move,₹50 Lac
...,...,...,...,...,...,...,...
2995,2995,3 BHK Apartment for Sale in Greenfield City Cl...,850 sqft,Semi-Furnished,Resale,Ready to Move,₹50 Lac
2996,2996,2 BHK Apartment for Sale in Classic Tower,1120 sqft,NaN,Resale,Ready to Move,₹1.50 Cr
2997,2997,1 BHK Apartment for Sale in Mukundapur Kolkata,272 sqft,NaN,Resale,Ready to Move,₹15 Lac
2998,2998,3 BHK Apartment for Sale in Koyla Vihar Vasund...,1800 sqft,NaN,Resale,Ready to Move,₹1.35 Cr
2999,2999,3 BHK Apartment for Sale in Lake Town Kolkata,928 sqft,NaN,NaN,Ready to Move,₹42 Lac

In [4]:
data.head(5)

,Unnamed: 0,Name,Area,Furnishing,Transaction,Status,Price
0,0,4 BHK Apartment for Sale in Sugam Morya,1850 sqft,Unfurnished,Resale,Ready to Move,₹2.38 Cr
1,1,2 BHK Apartment for Sale in Regent Park Kolkata,525 sqft,Unfurnished,Resale,Ready to Move,₹32 Lac
2,2,2 BHK Apartment for Sale in Parvati Garden,705 sqft,Unfurnished,Resale,Ready to Move,₹32 Lac
3,3,3 BHK Apartment for Sale in Multicon Estelle,1612 sqft,Unfurnished,Resale,Ready to Move,₹2.25 Cr
4,4,2 BHK Apartment for Sale in Golpark Cooperativ...,980 sqft,Semi-Furnished,Resale,Ready to Move,₹50 Lac

In [5]:
data.drop("Unnamed: 0",axis=1,inplace=True)

In [6]:
data.head(5)

,Name,Area,Furnishing,Transaction,Status,Price
0,4 BHK Apartment for Sale in Sugam Morya,1850 sqft,Unfurnished,Resale,Ready to Move,₹2.38 Cr
1,2 BHK Apartment for Sale in Regent Park Kolkata,525 sqft,Unfurnished,Resale,Ready to Move,₹32 Lac
2,2 BHK Apartment for Sale in Parvati Garden,705 sqft,Unfurnished,Resale,Ready to Move,₹32 Lac
3,3 BHK Apartment for Sale in Multicon Estelle,1612 sqft,Unfurnished,Resale,Ready to Move,₹2.25 Cr
4,2 BHK Apartment for Sale in Golpark Cooperativ...,980 sqft,Semi-Furnished,Resale,Ready to Move,₹50 Lac

In [7]:
data.isnull().sum()

Name             0
Area             0
Furnishing     377
Transaction    100
Status           0
Price            0
dtype: int64

In [8]:
data['Furnishing'].value_counts()

Furnishing
Unfurnished       1223
Semi-Furnished    1200
Furnished          200
Name: count, dtype: int64

In [9]:
for i in data.columns:
    print(f"describe the feature of {i} :")
    print(data[i].value_counts())
    print(".......................................................")

describe the feature of Name :
Name
4 BHK Apartment for Sale in Sugam Morya                            100
2 BHK Apartment for Sale in Regent Park Kolkata                    100
2 BHK Apartment for Sale in Parvati Garden                         100
3 BHK Apartment for Sale in Multicon Estelle                       100
2 BHK Apartment for Sale in Golpark Cooperative Housing Society    100
2 BHK Apartment for Sale in Shyam Vihar Phase 2                    100
Office Space for Sale in Ballygunge Kolkata                        100
3 BHK Apartment for Sale in Urban Heights                          100
3 BHK House for Sale in Thakurpukur Kolkata                        100
2 BHK Apartment for Sale in Rajarhat Kolkata                       100
2 BHK Apartment for Sale in Batanagar Kolkata                      100
2 BHK Builder Floor for Sale in Buroshibtalla                      100
2 BHK Apartment for Sale in Parnasree Palli Kolkata                100
3 BHK Apartment for Sale in Baguiati Kolkata                       100
3 BHK Apartment for Sale in Batanagar Kolkata                      100
3 BHK Apartment for Sale in Behala Kolkata                         100
3 BHK Apartment for Sale in Behala Chowrasta Kolkata               100
3 BHK House for Sale in Haridevpur                                 100
3 BHK Apartment for Sale in Motilal Gupta Road Kolkata             100
6 BHK House for Sale in Bangur Avenue                              100
5 BHK House for Sale in Ballygunge Kolkata                         100
2 BHK Apartment for Sale in Golf Towers                            100
Showroom for Sale in Kankurgachi Kolkata                           100
Shop for Sale in Meena Florence                                    100
3 BHK Apartment for Sale in Greenfield City Classic Premium        100
2 BHK Apartment for Sale in Classic Tower                          100
1 BHK Apartment for Sale in Mukundapur Kolkata                     100
3 BHK Apartment for Sale in Koyla Vihar Vasundhara                 100
3 BHK Apartment for Sale in Lake Town Kolkata                      100
Shop for Sale in Vip Road Kolkata                                   77
3 BHK Apartment for Sale in Shyam Vihar                             23
Name: count, dtype: int64
.......................................................
describe the feature of Area :
Area
850 sqft     200
750 sqft     200
580 sqft     177
1850 sqft    100
525 sqft     100
705 sqft     100
1612 sqft    100
980 sqft     100
268 sqft     100
1241 sqft    100
1836 sqft    100
1140 sqft    100
652 sqft     100
820 sqft     100
1000 sqft    100
720 sqft     100
1817 sqft    100
1100 sqft    100
4400 sqft    100
2142 sqft    100
853 sqft     100
1675 sqft    100
386 sqft     100
1120 sqft    100
272 sqft     100
1800 sqft    100
928 sqft     100
985 sqft      23
Name: count, dtype: int64
.......................................................
describe the feature of Furnishing :
Furnishing
Unfurnished       1223
Semi-Furnished    1200
Furnished          200
Name: count, dtype: int64
.......................................................
describe the feature of Transaction :
Transaction
Resale    2900
Name: count, dtype: int64
.......................................................
describe the feature of Status :
Status
Ready to Move    3000
Name: count, dtype: int64
.......................................................
describe the feature of Price :
Price
₹32 Lac     200
₹50 Lac     200
₹85 Lac     200
₹35 Lac     200
₹42 Lac     200
₹2.38 Cr    100
₹2.25 Cr    100
₹38 Lac     100
₹45 Lac     100
₹1.25 Cr    100
₹1.60 Cr    100
₹59 Lac     100
₹51 Lac     100
₹60 Lac     100
₹75 Lac     100
₹84 Lac     100
₹30 Lac     100
₹2.80 Cr    100
₹1.45 Cr    100
₹2.50 Cr    100
₹37 Lac     100
₹1.50 Cr    100
₹15 Lac     100
₹1.35 Cr    100
₹55 Lac      77
₹67 Lac      23
Name: count, dtype: int64
.......................................................

In [10]:
data.dropna(inplace=True)

In [11]:
for i in data.columns:
    print(f"describe the feature of {i} :")
    print(data[i].value_counts())
    print(".......................................................")

describe the feature of Name :
Name
4 BHK Apartment for Sale in Sugam Morya                            100
2 BHK Apartment for Sale in Regent Park Kolkata                    100
2 BHK Apartment for Sale in Parvati Garden                         100
3 BHK Apartment for Sale in Multicon Estelle                       100
2 BHK Apartment for Sale in Golpark Cooperative Housing Society    100
2 BHK Apartment for Sale in Shyam Vihar Phase 2                    100
Office Space for Sale in Ballygunge Kolkata                        100
3 BHK Apartment for Sale in Urban Heights                          100
3 BHK House for Sale in Thakurpukur Kolkata                        100
2 BHK Apartment for Sale in Rajarhat Kolkata                       100
2 BHK Apartment for Sale in Batanagar Kolkata                      100
2 BHK Builder Floor for Sale in Buroshibtalla                      100
2 BHK Apartment for Sale in Parnasree Palli Kolkata                100
3 BHK Apartment for Sale in Baguiati Kolkata                       100
3 BHK Apartment for Sale in Batanagar Kolkata                      100
3 BHK Apartment for Sale in Behala Kolkata                         100
3 BHK Apartment for Sale in Behala Chowrasta Kolkata               100
3 BHK House for Sale in Haridevpur                                 100
3 BHK Apartment for Sale in Motilal Gupta Road Kolkata             100
6 BHK House for Sale in Bangur Avenue                              100
5 BHK House for Sale in Ballygunge Kolkata                         100
2 BHK Apartment for Sale in Golf Towers                            100
Showroom for Sale in Kankurgachi Kolkata                           100
Shop for Sale in Meena Florence                                    100
3 BHK Apartment for Sale in Greenfield City Classic Premium        100
Shop for Sale in Vip Road Kolkata                                   77
2 BHK Apartment for Sale in Classic Tower                           23
1 BHK Apartment for Sale in Mukundapur Kolkata                      23
Name: count, dtype: int64
.......................................................
describe the feature of Area :
Area
850 sqft     200
750 sqft     200
580 sqft     177
1850 sqft    100
525 sqft     100
705 sqft     100
1612 sqft    100
980 sqft     100
268 sqft     100
1241 sqft    100
1836 sqft    100
1140 sqft    100
652 sqft     100
820 sqft     100
1000 sqft    100
720 sqft     100
1817 sqft    100
1100 sqft    100
4400 sqft    100
2142 sqft    100
853 sqft     100
1675 sqft    100
386 sqft     100
1120 sqft     23
272 sqft      23
Name: count, dtype: int64
.......................................................
describe the feature of Furnishing :
Furnishing
Unfurnished       1223
Semi-Furnished    1200
Furnished          200
Name: count, dtype: int64
.......................................................
describe the feature of Transaction :
Transaction
Resale    2623
Name: count, dtype: int64
.......................................................
describe the feature of Status :
Status
Ready to Move    2623
Name: count, dtype: int64
.......................................................
describe the feature of Price :
Price
₹32 Lac     200
₹50 Lac     200
₹85 Lac     200
₹35 Lac     200
₹2.38 Cr    100
₹2.25 Cr    100
₹38 Lac     100
₹45 Lac     100
₹1.25 Cr    100
₹1.60 Cr    100
₹59 Lac     100
₹51 Lac     100
₹60 Lac     100
₹42 Lac     100
₹75 Lac     100
₹84 Lac     100
₹30 Lac     100
₹2.80 Cr    100
₹1.45 Cr    100
₹2.50 Cr    100
₹37 Lac     100
₹55 Lac      77
₹1.50 Cr     23
₹15 Lac      23
Name: count, dtype: int64
.......................................................

In [12]:
data['Name'].head(10)

0              4 BHK Apartment for Sale in Sugam Morya
1      2 BHK Apartment for Sale in Regent Park Kolkata
2           2 BHK Apartment for Sale in Parvati Garden
3         3 BHK Apartment for Sale in Multicon Estelle
4    2 BHK Apartment for Sale in Golpark Cooperativ...
5      2 BHK Apartment for Sale in Shyam Vihar Phase 2
6          Office Space for Sale in Ballygunge Kolkata
7                    Shop for Sale in Vip Road Kolkata
8            3 BHK Apartment for Sale in Urban Heights
9          3 BHK House for Sale in Thakurpukur Kolkata
Name: Name, dtype: str

In [13]:
data[['House_type','Location']]=data['Name'].str.split('for Sale in',expand=True)

In [14]:
data.head(5)

,Name,Area,Furnishing,Transaction,Status,Price,House_type,Location
0,4 BHK Apartment for Sale in Sugam Morya,1850 sqft,Unfurnished,Resale,Ready to Move,₹2.38 Cr,4 BHK Apartment,Sugam Morya
1,2 BHK Apartment for Sale in Regent Park Kolkata,525 sqft,Unfurnished,Resale,Ready to Move,₹32 Lac,2 BHK Apartment,Regent Park Kolkata
2,2 BHK Apartment for Sale in Parvati Garden,705 sqft,Unfurnished,Resale,Ready to Move,₹32 Lac,2 BHK Apartment,Parvati Garden
3,3 BHK Apartment for Sale in Multicon Estelle,1612 sqft,Unfurnished,Resale,Ready to Move,₹2.25 Cr,3 BHK Apartment,Multicon Estelle
4,2 BHK Apartment for Sale in Golpark Cooperativ...,980 sqft,Semi-Furnished,Resale,Ready to Move,₹50 Lac,2 BHK Apartment,Golpark Cooperative Housing Society

In [15]:
data['House_type'].value_counts()

House_type
2 BHK Apartment         823
3 BHK Apartment         800
3 BHK House             200
Shop                    177
4 BHK Apartment         100
Office Space            100
2 BHK Builder Floor     100
6 BHK House             100
5 BHK House             100
Showroom                100
1 BHK Apartment          23
Name: count, dtype: int64

In [16]:
data['House_type'] = data['House_type'].str.strip()

In [17]:
data['House_type']=data['House_type'].replace({'Shop':'1 BHK Shop','Office Space':'1 BHK Office Space','Showroom':'1 BHK Showroom'})

In [18]:
data['House_type'].value_counts()

House_type
2 BHK Apartment        823
3 BHK Apartment        800
3 BHK House            200
1 BHK Shop             177
4 BHK Apartment        100
1 BHK Office Space     100
2 BHK Builder Floor    100
6 BHK House            100
5 BHK House            100
1 BHK Showroom         100
1 BHK Apartment         23
Name: count, dtype: int64

In [19]:
data[['BHK','House_Type']]=data['House_type'].str.split(' BHK ',expand=True)

In [20]:
data.head(5)

,Name,Area,Furnishing,Transaction,Status,Price,House_type,Location,BHK,House_Type
0,4 BHK Apartment for Sale in Sugam Morya,1850 sqft,Unfurnished,Resale,Ready to Move,₹2.38 Cr,4 BHK Apartment,Sugam Morya,4,Apartment
1,2 BHK Apartment for Sale in Regent Park Kolkata,525 sqft,Unfurnished,Resale,Ready to Move,₹32 Lac,2 BHK Apartment,Regent Park Kolkata,2,Apartment
2,2 BHK Apartment for Sale in Parvati Garden,705 sqft,Unfurnished,Resale,Ready to Move,₹32 Lac,2 BHK Apartment,Parvati Garden,2,Apartment
3,3 BHK Apartment for Sale in Multicon Estelle,1612 sqft,Unfurnished,Resale,Ready to Move,₹2.25 Cr,3 BHK Apartment,Multicon Estelle,3,Apartment
4,2 BHK Apartment for Sale in Golpark Cooperativ...,980 sqft,Semi-Furnished,Resale,Ready to Move,₹50 Lac,2 BHK Apartment,Golpark Cooperative Housing Society,2,Apartment

In [21]:
data['Status'].value_counts()

Status
Ready to Move    2623
Name: count, dtype: int64

In [22]:
data['Transaction'].value_counts()

Transaction
Resale    2623
Name: count, dtype: int64

In [23]:
data.drop(['Name','House_type','Status','Transaction'],axis=1,inplace=True)

In [24]:
data.head(5)

,Area,Furnishing,Price,Location,BHK,House_Type
0,1850 sqft,Unfurnished,₹2.38 Cr,Sugam Morya,4,Apartment
1,525 sqft,Unfurnished,₹32 Lac,Regent Park Kolkata,2,Apartment
2,705 sqft,Unfurnished,₹32 Lac,Parvati Garden,2,Apartment
3,1612 sqft,Unfurnished,₹2.25 Cr,Multicon Estelle,3,Apartment
4,980 sqft,Semi-Furnished,₹50 Lac,Golpark Cooperative Housing Society,2,Apartment

In [25]:
data.rename(columns={'Area':'Area(sqft)'},inplace=True)

In [26]:
data['Area(sqft)'] = data['Area(sqft)'].str.replace('sqft', '').astype(int)

In [27]:
data.head(5)

,Area(sqft),Furnishing,Price,Location,BHK,House_Type
0,1850,Unfurnished,₹2.38 Cr,Sugam Morya,4,Apartment
1,525,Unfurnished,₹32 Lac,Regent Park Kolkata,2,Apartment
2,705,Unfurnished,₹32 Lac,Parvati Garden,2,Apartment
3,1612,Unfurnished,₹2.25 Cr,Multicon Estelle,3,Apartment
4,980,Semi-Furnished,₹50 Lac,Golpark Cooperative Housing Society,2,Apartment

In [28]:
def convert_price_to_crores(price_str):
    price_str = str(price_str).replace('₹', '').strip()
    if 'Cr' in price_str:
        return float(price_str.replace('Cr', '').strip())
    elif 'Lac' in price_str:
        return float(price_str.replace('Lac', '').strip()) / 100  # Convert Lac to Cr
    return np.nan # Handle any other cases, though based on value_counts, these are the main ones

data['Price'] = data['Price'].apply(convert_price_to_crores)

In [29]:
data.rename(columns={'Price':'Price(cr)'},inplace=True)

In [30]:
data.head(5)

,Area(sqft),Furnishing,Price(cr),Location,BHK,House_Type
0,1850,Unfurnished,2.38,Sugam Morya,4,Apartment
1,525,Unfurnished,0.32,Regent Park Kolkata,2,Apartment
2,705,Unfurnished,0.32,Parvati Garden,2,Apartment
3,1612,Unfurnished,2.25,Multicon Estelle,3,Apartment
4,980,Semi-Furnished,0.50,Golpark Cooperative Housing Society,2,Apartment

##checking is split create space or not

In [31]:
data['has_leading_space'] = data['Location'].str.startswith(' ')

In [32]:
data['has_leading_space2'] = data['House_Type'].str.startswith(' ')

In [33]:
data['has_leading_space3'] = data['BHK'].str.startswith(' ')

In [34]:
data

,Area(sqft),Furnishing,Price(cr),Location,BHK,House_Type,has_leading_space,has_leading_space2,has_leading_space3
0,1850,Unfurnished,2.38,Sugam Morya,4,Apartment,True,False,False
1,525,Unfurnished,0.32,Regent Park Kolkata,2,Apartment,True,False,False
2,705,Unfurnished,0.32,Parvati Garden,2,Apartment,True,False,False
3,1612,Unfurnished,2.25,Multicon Estelle,3,Apartment,True,False,False
4,980,Semi-Furnished,0.50,Golpark Cooperative Housing Society,2,Apartment,True,False,False
...,...,...,...,...,...,...,...,...,...
2991,853,Unfurnished,0.85,Golf Towers,2,Apartment,True,False,False
2992,580,Semi-Furnished,0.55,Vip Road Kolkata,1,Shop,True,False,False
2993,1675,Semi-Furnished,2.50,Kankurgachi Kolkata,1,Showroom,True,False,False
2994,386,Unfurnished,0.37,Meena Florence,1,Shop,True,False,False
2995,850,Semi-Furnished,0.50,Greenfield City Classic Premium,3,Apartment,True,False,False

In [35]:
data['has_leading_space'].value_counts()

has_leading_space
True    2623
Name: count, dtype: int64

In [36]:
data['has_leading_space2'].value_counts()

has_leading_space2
False    2623
Name: count, dtype: int64

In [37]:
data['has_leading_space3'].value_counts()

has_leading_space3
False    2623
Name: count, dtype: int64

In [38]:
data['Location'] = data['Location'].str.strip()

In [39]:
data['has_leading_space4'] = data['Location'].str.startswith(' ')

In [40]:
data['has_leading_space4'].value_counts()

has_leading_space4
False    2623
Name: count, dtype: int64

In [41]:
data.head(5)

,Area(sqft),Furnishing,Price(cr),Location,BHK,House_Type,has_leading_space,has_leading_space2,has_leading_space3,has_leading_space4
0,1850,Unfurnished,2.38,Sugam Morya,4,Apartment,True,False,False,False
1,525,Unfurnished,0.32,Regent Park Kolkata,2,Apartment,True,False,False,False
2,705,Unfurnished,0.32,Parvati Garden,2,Apartment,True,False,False,False
3,1612,Unfurnished,2.25,Multicon Estelle,3,Apartment,True,False,False,False
4,980,Semi-Furnished,0.50,Golpark Cooperative Housing Society,2,Apartment,True,False,False,False

In [42]:
data.drop(['has_leading_space','has_leading_space2','has_leading_space3','has_leading_space4'],axis=1,inplace=True)

In [43]:
data.head(5)

,Area(sqft),Furnishing,Price(cr),Location,BHK,House_Type
0,1850,Unfurnished,2.38,Sugam Morya,4,Apartment
1,525,Unfurnished,0.32,Regent Park Kolkata,2,Apartment
2,705,Unfurnished,0.32,Parvati Garden,2,Apartment
3,1612,Unfurnished,2.25,Multicon Estelle,3,Apartment
4,980,Semi-Furnished,0.50,Golpark Cooperative Housing Society,2,Apartment

In [44]:
data['House_Type'].value_counts()

House_Type
Apartment        1746
House             400
Shop              177
Office Space      100
Builder Floor     100
Showroom          100
Name: count, dtype: int64

In [45]:
data['House_Type'].value_counts()

House_Type
Apartment        1746
House             400
Shop              177
Office Space      100
Builder Floor     100
Showroom          100
Name: count, dtype: int64

In [94]:
data['BHK'].value_counts()

BHK
3    1000
2     923
1     400
4     100
6     100
5     100
Name: count, dtype: int64

need to use pipeline to separate the numarical and catagorical data

In [46]:
X=data.drop('Price(cr)',axis=1)
Y=data['Price(cr)']

In [47]:
X.head(5)

,Area(sqft),Furnishing,Location,BHK,House_Type
0,1850,Unfurnished,Sugam Morya,4,Apartment
1,525,Unfurnished,Regent Park Kolkata,2,Apartment
2,705,Unfurnished,Parvati Garden,2,Apartment
3,1612,Unfurnished,Multicon Estelle,3,Apartment
4,980,Semi-Furnished,Golpark Cooperative Housing Society,2,Apartment

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

##PREPROSSESING STEP:COLUMN TRANSFORMAR

In [50]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [51]:
preprosser=ColumnTransformer(
    transformers=[
        ('categorical_data_trans', OneHotEncoder(handle_unknown='ignore', sparse_output=False), ['Location','Furnishing','House_Type'])
    ],
    remainder='passthrough'
)

In [52]:
from sklearn.pipeline import Pipeline

##LinearRegression

In [53]:
from sklearn.linear_model import LinearRegression

In [54]:
lr=LinearRegression()
model_pipeline=Pipeline(steps=[
    ('preprosser',preprosser),
    ('model',lr)
])

In [55]:
from sklearn import set_config
set_config(display='diagram')
model_pipeline

Pipeline(steps=[('preprosser',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('categorical_data_trans',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Location', 'Furnishing',
                                                   'House_Type'])])),
                ('model', LinearRegression())])

In [56]:
model_pipeline.fit(X_train,Y_train)

Pipeline(steps=[('preprosser',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('categorical_data_trans',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Location', 'Furnishing',
                                                   'House_Type'])])),
                ('model', LinearRegression())])

In [57]:
Y_predict=model_pipeline.predict(X_test)

In [58]:
from sklearn.metrics import r2_score

In [59]:
r2_linear = r2_score(Y_test, Y_predict)
print("R² Score:", r2_linear)

R² Score: 1.0

##ridge Regression

In [60]:
from sklearn.linear_model import Ridge

In [61]:
re=Ridge()
model_pipeline_ridge=Pipeline(steps=[
    ('preprosser',preprosser),
    ('model',re)
])

In [62]:
model_pipeline_ridge.fit(X_train,Y_train)

Pipeline(steps=[('preprosser',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('categorical_data_trans',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Location', 'Furnishing',
                                                   'House_Type'])])),
                ('model', Ridge())])

In [63]:
predict2=model_pipeline_ridge.predict(X_test)

In [64]:
r2_ridge= r2_score(Y_test,predict2)
print("R² Score:", r2_ridge)

R² Score: 0.999930727600374

##lasso Regression

In [65]:
from sklearn.linear_model import Lasso

In [66]:
lasso=Lasso()
model_pipeline_lasso=Pipeline(steps=[
    ('preprosser',preprosser),
    ('model',lasso)
])

In [67]:
model_pipeline_lasso.fit(X_train,Y_train)

Pipeline(steps=[('preprosser',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('categorical_data_trans',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Location', 'Furnishing',
                                                   'House_Type'])])),
                ('model', Lasso())])

In [68]:
predict3=model_pipeline_lasso.predict(X_test)

In [69]:
r2_lasso= r2_score(Y_test,predict3)
print("R² Score:", r2_lasso)

R² Score: 0.5842065189459739

##Decision_Tree_Regressor

In [70]:
from sklearn.tree import DecisionTreeRegressor

In [71]:
model = DecisionTreeRegressor(
    max_depth=5,
    random_state=42
)
model_pipeline_D_T_R=Pipeline(steps=[
    ('preprosser',preprosser),
    ('model',model)
])

In [72]:
model_pipeline_D_T_R.fit(X_train,Y_train)

Pipeline(steps=[('preprosser',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('categorical_data_trans',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Location', 'Furnishing',
                                                   'House_Type'])])),
                ('model', DecisionTreeRegressor(max_depth=5, random_state=42))])

In [73]:
predict4=model_pipeline_D_T_R.predict(X_test)

In [74]:
r2_decision= r2_score(Y_test,predict4)
print("R² Score:", r2_decision)

R² Score: 0.9931201044198714

##Random Forest Regressor

In [75]:
from sklearn.ensemble import RandomForestRegressor

In [76]:
model_random = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)
model_pipeline_random=Pipeline(steps=[
    ('preprosser',preprosser),
    ('model',model_random)
])

In [77]:
model_pipeline_random.fit(X_train,Y_train)

Pipeline(steps=[('preprosser',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('categorical_data_trans',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Location', 'Furnishing',
                                                   'House_Type'])])),
                ('model', RandomForestRegressor(random_state=42))])

In [78]:
predict5=model_pipeline_random.predict(X_test)

In [79]:
r2_randomF= r2_score(Y_test,predict5)
print("R² Score:", r2_randomF)

R² Score: 1.0

##SVR

In [80]:
from sklearn.svm import SVR

In [81]:
model_svr=SVR(
        kernel='rbf',
        C=100,
        gamma='scale'
    )
model_pipeline_svr=Pipeline(steps=[
    ('preprosser',preprosser),
    ('model',model_svr)
])

In [82]:
model_pipeline_svr.fit(X_train,Y_train)

Pipeline(steps=[('preprosser',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('categorical_data_trans',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Location', 'Furnishing',
                                                   'House_Type'])])),
                ('model', SVR(C=100))])

In [83]:
predict6=model_pipeline_svr.predict(X_test)

In [84]:
r2_SVR= r2_score(Y_test,predict6)
print("R² Score:", r2_SVR)

R² Score: 0.609955514805966

###go with Random Forest Regressor

In [85]:
data.head(5)

,Area(sqft),Furnishing,Price(cr),Location,BHK,House_Type
0,1850,Unfurnished,2.38,Sugam Morya,4,Apartment
1,525,Unfurnished,0.32,Regent Park Kolkata,2,Apartment
2,705,Unfurnished,0.32,Parvati Garden,2,Apartment
3,1612,Unfurnished,2.25,Multicon Estelle,3,Apartment
4,980,Semi-Furnished,0.50,Golpark Cooperative Housing Society,2,Apartment

In [86]:
import pickle
pickle.dump(model_pipeline_random,open('model5.pkl','wb'))
pickle.dump(data,open('data.pkl','wb'))

##Acctual prediction

In [87]:
new_data=pd.DataFrame([['386','Unfurnished','Meena Florence','1','Shop']],
                      columns=['Area(sqft)','Furnishing','Location','BHK','House_Type'])

In [88]:
new_data

  Area(sqft)   Furnishing        Location BHK House_Type
0        386  Unfurnished  Meena Florence   1       Shop

In [89]:
model_pipeline_random.predict(new_data)

array([0.37])

In [90]:
new_data2=pd.DataFrame([['1612','Unfurnished','Multicon Estelle','3','Apartment']],
                      columns=['Area(sqft)','Furnishing','Location','BHK','House_Type'])

In [91]:
new_data2

  Area(sqft)   Furnishing          Location BHK House_Type
0       1612  Unfurnished  Multicon Estelle   3  Apartment

In [92]:
model_pipeline_random.predict(new_data2)

array([2.25])

In [93]:
data.head(5)

,Area(sqft),Furnishing,Price(cr),Location,BHK,House_Type
0,1850,Unfurnished,2.38,Sugam Morya,4,Apartment
1,525,Unfurnished,0.32,Regent Park Kolkata,2,Apartment
2,705,Unfurnished,0.32,Parvati Garden,2,Apartment
3,1612,Unfurnished,2.25,Multicon Estelle,3,Apartment
4,980,Semi-Furnished,0.50,Golpark Cooperative Housing Society,2,Apartment